### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by muditp2012** [iagox86/dnscat2#162]
I was trying to upload a file from linux system to windows system and got following error:

command (els-DB) 1> upload /home/kali//prodump64.exe c:\Windows\Temp\procdump64.exe
Something bad just happened! You will likely want to report this to
https://github.com/iagox86/dnscat2/issues
#<Errno::ENOENT: No such file or directory @ rb_sysopen - /home/kali/ecptxv2/prodump64.exe>
/home/kali/ecptxv2/dnscat2/server/drivers/driver_command_commands.rb:199:in `read'
/home/kali/ecptxv2/dnscat2/server/drivers/driver_command_commands.rb:199:in `block in _register_commands'
/home/kali/ecptxv2/dnscat2/server/libs/commander.rb:132:in `feed'
/home/kali/ecptxv2/dnscat2/server/drivers/driver_command.rb:81:in `block in initialize'
/home/kali/ecptxv2/dnscat2/server/libs/swindow.rb:319:in `_incoming'
/home/kali/ecptxv2/dnscat2/server/libs/swindow.rb:105:in `block (3 levels) in <class:SWindow>'
/home/kali/ecptxv2/dnscat2/server/libs/swindow.rb:80:in `loop'
/home/kali/ecptxv2/dnscat2/server/libs/swindow.rb:80:in `block (2 levels) in <class:SWindow>'
/home/kali/ecptxv2/dnscat2/server/libs/swindow.rb:70:in `_catch_suspend'
/home/kali/ecptxv2/dnscat2/server/libs/swindow.rb:79:in `block in <class:SWindow>'

**Comment by janedoe-lab** [comment]
@muditp2012, you want to use forward slashes instead of backslashes in the windows path

**Comment by isgapetti** [comment]
Bump, upload still does not work

**Comment by iagox86** [comment]
I don't really maintain this anymore, I know it's kinda buggy but at this
point it is what it is
