### ISSUE TITLE
undefined method `peek_session_id' for Packet:Module

### ISSUE THREAD

**Issue by iagox86** [iagox86/dnscat2#60]
From the reporter:

I recently downloaded the latest git of dnscat2.  I've received the following error.  Have you seen the error below before?  It happens as the client reaches out to initiate a session with the server.  client receives "[[ ERROR ]] :: DNS : RCODE_NAME_ERROR".

    dnscat2> [ERROR] [NoMethodError]: undefined method `peek_session_id' for Packet:Module
    [ERROR] /root/dnscat2/server/session_manager.rb:112:in `block in go'
    [ERROR] /root/dnscat2/server/driver_dns.rb:226:in `block (2 levels) in recv'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:217:in `[]'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:217:in `call'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:327:in `block (2 levels) in process'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:325:in `catch'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:325:in `block in process'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:322:in `each'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:322:in `process'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/transaction.rb:192:in `process'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:106:in `block in process_query'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:98:in `each'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/server.rb:98:in `process_query'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/handler.rb:55:in `process_query'
    [ERROR] /root/.gems/gems/rubydns-1.0.1/lib/rubydns/handler.rb:87:in `respond'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    [ERROR] /root/.gems/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    [ERROR] Propagating the exception...

**Comment by iagox86** [comment]
Looking at that code, I have no idea how that can possibly happen.

The line in question is:

112         session_id = Packet.peek_session_id(data)

Which is calling a static method on the class Packet:

283   def Packet.peek_session_id(data)
284     _, _, session_id, _ = Packet.parse_header(data)
285
286     return session_id
287   end

and that should always exist.

My only thoughts are:

1. Is something else called 'Packet' interfering?

2. Is this an issue with ruby versions? I'm using 1.9 to test.

**Comment by iagox86** [comment]
I don't think this behaviour is possible without some kind of weird environment, and the reporter hasn't gotten back to me after repeated attempts. I'm gonna go ahead and close this.
