### ISSUE TITLE
Server, ruby error

### ISSUE THREAD

**Issue by Swiffers** [iagox86/dnscat2#65]
Following your installation manual, with a Droplet from https://cloud.digitalocean.com;
I end up with the following error : 
```
ruby ./dnscat2.rb
```
```
/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find rexec (~> 1.6.2) amongst [bundler-1.10.6, eventmachine-1.0.3, rubydns-0.7.3, trollop-2.0] (Gem::LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:777:in `block in activate_dependencies'
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:766:in `each'
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:766:in `activate_dependencies'
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:750:in `activate'
	from /usr/lib/ruby/1.9.1/rubygems.rb:212:in `rescue in try_activate'
	from /usr/lib/ruby/1.9.1/rubygems.rb:209:in `try_activate'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from /root/dnscat2/server/driver_dns.rb:11:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from ./dnscat2.rb:14:in `<main>'
```

**Comment by iagox86** [comment]
I think that's somewhere in the install guide.. you have to install
"ruby-dev" or something. I can look it up later. :)

**Comment by iagox86** [comment]
So, that's not the error I was thinking of, the one I noticed looked like:

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)

And installing the "ruby-dev" package worked. It's possible I just have to add "rexec" to the gemfile. If installing "ruby-dev" doesn't help, can you run "gem install rexec" and see if that helps?

**Comment by Swiffers** [comment]
Issue solved ! 
Installing the rexec gem fixed the problem.
```
gem install rexec
```

**Comment by iagox86** [comment]
Great! I added it to the Gemfile explicitly.
