### ISSUE TITLE
gem install ecdsa -v '1.2.0'  ERROR

### ISSUE THREAD

**Issue by mehranexpert** [iagox86/dnscat2#96]
i using bundle install to install it ,  i got error  ;

An error occurred while installing ecdsa (1.2.0), and Bundler cannot continue.
Make sure that `gem install ecdsa -v '1.2.0'` succeeds before bundling.

im try `gem install ecdsa -v '1.2.0'`

i got error `
ERROR:  Error installing ecdsa:
        ecdsa requires RubyGems version >= 2. Try 'gem update --system' to update RubyGems itself.`

and 

gem update --system
ERROR:  While executing gem ... (RuntimeError)
    gem update --system is disabled on Debian, because it will overwrite the content of the rubygems Debian package, and might break your Debian system in subtle ways. The Debian-supported way to update rubygems is through apt-get, using Debian official repositories.
If you really know what you are doing, you can still update rubygems by setting the REALLY_GEM_UPDATE_SYSTEM environment variable, but please remember that this is completely unsupported by Debian.

now what am i doing ?

**Comment by mehranexpert** [comment]
i fixed that now i got new Error : 

`
/usr/local/lib/site_ruby/1.9.1/rubygems/dependency.rb:308:in `to_specs': Could not find 'bundler' (>= 0) among 1 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/root/.gem/ruby/1.9.1:/usr/lib/ruby/gems/1.9.1', execute `gem env` for more information
        from /usr/local/lib/site_ruby/1.9.1/rubygems/dependency.rb:320:in `to_spec'
        from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from /usr/local/bin/bundle:22:in `<main>'
`

**Comment by mirkathaha** [comment]
do a "sudo gem install bundler" and then "sudo bundle install" again
