### ISSUE TITLE
I killed a session of dnscat2-powershell and got many errors

### ISSUE THREAD

**Issue by donvitoz** [iagox86/dnscat2#99]
An error occurred (see window 1 for stacktrace): MSG received in invalid state!
An error occurred (see window 1 for stacktrace): MSG received in invalid state!
An error occurred (see window 1 for stacktrace): MSG received in invalid state!
An error occurred (see window 1 for stacktrace): MSG received in invalid state!

If you think this might be a bug, please report this trace:
#<DnscatException: MSG received in invalid state!>
/root/dnscat2/server/controller/session.rb:207:in `_handle_msg'
/root/dnscat2/server/controller/session.rb:387:in `_handle_incoming'
/root/dnscat2/server/controller/session.rb:405:in `block in feed'
/root/dnscat2/server/controller/encryptor.rb:244:in `decrypt_and_encrypt'
/root/dnscat2/server/controller/session.rb:395:in `feed'
/root/dnscat2/server/controller/controller.rb:91:in `feed'
/root/dnscat2/server/tunnel_drivers/tunnel_drivers.rb:25:in `block in start'
/root/dnscat2/server/tunnel_drivers/driver_dns.rb:316:in `block in initialize'
/root/dnscat2/server/libs/dnser.rb:872:in `block (2 levels) in on_request'
/root/dnscat2/server/libs/dnser.rb:843:in `loop'
/root/dnscat2/server/libs/dnser.rb:843:in `block in on_request'
An error occurred (see window 1 for stacktrace): MSG received in invalid state!

**Comment by iagox86** [comment]
Wow, dnscat2-powershell actually works!? It was written a few versions ago,
didn't realize it was still working. :)

It sounds like after the connection ended, something kept on sending MSG
packets, which are standard data packets. That could be recursive DNS
servers that haven't realized it's over yet, or it could be that the client
doesn't realize it shut down.

I suspect it's not a big deal, unless this broke something - it just sounds
like the client sent a terminator packet then kept sending MSG.

If this is actually a problem, more details or a repro would be helpful
(what exactly you did on the client and server, what you expected to
happen, and what actually happened).

Thanks!
